**Haftalık Ödev – Yaz Kampı: Veri Bilimi – Hafta 3**

Soru 1 – Liste Metotları

Bir sınıfta öğrencilerin notları şu şekilde tutuluyor:

notlar = [85, 92, 76, 92, 100, 76, 85, 92]
• Listedeki tekrar eden notları silip benzersiz bir liste oluşturun.
• En yüksek ve en düşük notu bulun.
• Notları küçükten büyüğe sıralayın.

In [ ]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
yeni_liste = []
for i in notlar:
    if i not in yeni_liste:
        yeni_liste.append(i)
print( yeni_liste)

en_yuksek_not = max(yeni_liste)
en_dusuk_not = min(yeni_liste)
print("En yüksek not:", en_yuksek_not)
print("En düşük not:", en_dusuk_not)

yeni_liste.sort()
print("Küçükten büyüğe sıralanmış liste:", yeni_liste)

[85, 92, 76, 100]
En yüksek not: 100
En düşük not: 76
Küçükten büyüğe sıralanmış liste: [76, 85, 92, 100]


Soru 2 – Sayılar

Bir sayının Armstrong sayısı olup olmadığını kontrol eden bir Python fonksiyonu yazın.

Armstrong sayısı: Her basamağının küplerinin toplamı kendisine eşit olan sayılar.
Örn: 153 → 1³+5³+3³ = 153

In [ ]:
def armstrong_sayi(sayi):
  basamaklar = [int(x) for x in str(sayi)]
  toplam = sum([b ** 3 for b in basamaklar])
  if toplam == sayi:
    return True
  else:
    return False

sayi = int(input("Bir sayı girin: "))
if armstrong_sayi(sayi):
  print(sayi, "bir Armstrong sayısıdır.")
else:
  print(sayi, "bir Armstrong sayısı değildir.")


Soru 3 – Kümeler

Aşağıdaki iki küme verilmiştir:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
• Ortak dilleri bulun.
• Sadece A’da olan dilleri listeleyin.
• İki kümenin birleşimini alfabetik olarak yazdırın.

In [ ]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
ortak_dil = A & B
print("ortak diller:", ortak_dil)

sadece_a = A - B
print("Sadece A'da olan diller:", sadece_a)

birlesim = sorted(A | B)
print("İki kümenin birleşimleri:", birlesim)

Soru 4 – Modüller

• random modülünü kullanarak 1–100 arasında 10 rastgele sayı üretin.
• Bu sayıların ortalamasını ve standart sapmasını statistics modülü ile hesaplayın.


In [ ]:
import random
import statistics

rastgele_sayilar = [random.randint(1, 100) for _ in range(10)]
print("Üretilen rastgele sayılar:", rastgele_sayilar)


ortalama = statistics.mean(rastgele_sayilar)
standart_sapma = statistics.stdev(rastgele_sayilar)

print("Ortalama:", ortalama)
print("Standart sapma:", standart_sapma)

Üretilen rastgele sayılar: [75, 83, 52, 28, 40, 100, 77, 70, 36, 11]
Ortalama: 57.2
Standart sapma: 28.145652910845357


Soru 5 – Fonksiyonlar

kelime_sayacı(metin) adında bir fonksiyon yazın.
Fonksiyon verilen metindeki:

• toplam kelime sayısını
• en uzun kelimeyi
• en sık geçen kelimeyi döndürsün.

In [ ]:
metin = "Veri bilimi yaz kampında veri bilimine giriş eğitimi almaya başladım."
from collections import Counter

def kelime_bilgileri(metin):
    kelimeler = metin.split()
    kelime_sayisi = len(kelimeler)
    en_uzun_kelime = max(kelimeler, key=len)
    en_sik_kelime = Counter(kelimeler).most_common(1)[0][0]
    return kelime_sayisi, en_uzun_kelime, en_sik_kelime

kelime_sayisi, en_uzun_kelime, en_sik_kelime = kelime_bilgileri(metin)

print("Kelime sayısı:", kelime_sayisi)
print("En uzun kelime:", en_uzun_kelime)
print("En sık geçen kelime:", en_sik_kelime)


Kelime sayısı: 10
En uzun kelime: başladım.
En sık geçen kelime: Veri


Soru 6 – Gömülü Fonksiyonlar

Aşağıdaki liste için map, filter, sorted gibi gömülü fonksiyonları kullanarak:

sayilar = [5, 12, 7, 18, 24, 3, 16]

• Sadece çift sayıları filtreleyin.
• Bu sayıların karelerini bulun.
• Karelerini azalan sırada sıralayın.

In [9]:
sayilar = [5, 12, 7, 18, 24, 3, 16]
sonuc = filter(lambda x: x % 2 == 0, sayilar)
print("Çift sayılar:",list(sonuc) )

kareler = list(map(lambda x: x ** 2, sayilar))
print("Sayıların kareleri", list(kareler))

siralama = sorted(  kareler, reverse = True)
print("Azalan liste:", siralama)


Çift sayılar: [12, 18, 24, 16]
Sayıların kareleri [25, 144, 49, 324, 576, 9, 256]
Azalan liste: [576, 324, 256, 144, 49, 25, 9]


Soru 7 – Lambda İfadeleri

Aşağıdaki listeyi, her kelimenin uzunluğuna göre küçükten büyüğe sıralayın.

kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

Bunu sorted + lambda ile yapın.

In [10]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
siralama = sorted(kelimeler, key=lambda x: len(x))
print(siralama)

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


Soru 8 – Metodlar

Bir string içinde geçen tüm rakamları bulun ve bunların toplamını döndüren bir fonksiyon
yazın.
Örn: "abc12def3" → 12 + 3 = 15

In [11]:
string = "123veribilimiyazkampı456"
def rakam_toplami(string):
    rakamlar = [int(i) for i in string if i.isdigit()]
    toplam = sum(rakamlar)
    return toplam
print(rakam_toplami(string))

21


Soru 9 – (Ekstra) Numpy 1  

10 elemanlı bir numpy dizisi oluşturun.
• Elemanlar 0–50 arasında rastgele sayılar olsun.
• Dizinin ortalamasını, standart sapmasını ve en büyük değerini bulun.


In [14]:
import numpy as np

dizi = np.random.randint(0, 51, size=10)
print("Dizi:", dizi)

ortalama = np.mean(dizi)

std_sapma = np.std(dizi)

en_buyuk = np.max(dizi)

print("Ortalama:", ortalama)
print("Standart Sapma:", std_sapma)
print("En Büyük Değer:", en_buyuk)


Dizi: [ 1 33 23 15 34 38 19 41 20 43]
Ortalama: 26.7
Standart Sapma: 12.673200069437868
En Büyük Değer: 43


Soru 10 – (Ekstra) Numpy 2

5x5 boyutunda rastgele 0–1 arasında değerlerden oluşan bir numpy matrisi üretin.

• Her sütunun ortalamasını bulun.

• 0.5’ten büyük olan değerleri 1, küçük eşit olanları 0 yaparak binary matris oluşturun.

In [16]:
import numpy as np

matris = np.random.rand(5, 5)
print("Orijinal Matris:\n", matris)

sutun_ort = np.mean(matris, axis=0)
print("\nSütun Ortalamaları:", sutun_ort)

binary_matris = (matris > 0.5).astype(int)
print("\nBinary Matris:\n", binary_matris)


Orijinal Matris:
 [[0.17327392 0.58577388 0.92446882 0.54500253 0.79780219]
 [0.49097522 0.47049588 0.48473439 0.41319305 0.87173404]
 [0.71691686 0.20106359 0.51094765 0.90238454 0.12841918]
 [0.98724852 0.82941318 0.53863152 0.16187889 0.80541372]
 [0.70271025 0.9073499  0.60736966 0.62525203 0.86733517]]

Sütun Ortalamaları: [0.61422496 0.59881928 0.61323041 0.52954221 0.69414086]

Binary Matris:
 [[0 1 1 1 1]
 [0 0 0 0 1]
 [1 0 1 1 0]
 [1 1 1 0 1]
 [1 1 1 1 1]]
